config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from .settings.base import DEBUG

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('record/', include('record.urls')),
    path('devolution/', include('devolution.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
#        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ]

main/urls.py
from django.urls import path,include
from . import views
# from .views import LocationCreateFormView

app_name='main'
urlpatterns=[
    # Top index view
    path('', views.IndexView.as_view(), name='main_index'),
    # path('user/', views.user_view, name='main_user'),
    path('other/', views.other_view, name='main_other'),
    # Main detail view
    path('detail/<int:pk>/', views.MainDetailView.as_view(), name='main_detail'),
    path('user/', views.MainDetailView.as_view(), name='main_user'),
    # Location list view
    path('location/list', views.LocationListView.as_view(), name='location_list'),
    # Location list view
    # path('location/select', views.LocationSelectView.as_view(), name='location_select'),
    # Detail view
    path('location/detail/<int:pk>/', views.LocationDetailView.as_view(), name='location_detail'),
    # Location create view
    path('location/create/', views.LocationCreateModelFormView.as_view(), name='location_create'),
    # Location update view
    path('location/update/<int:pk>/', views.LocationUpdateModelFormView.as_view(), name='location_update'),    
    # Location delete view
    path('location/delete/<int:pk>/', views.LocationDeleteView.as_view(), name='location_delete'),
    
    # Sensors list view
    path('sensors/list', views.SensorsListView.as_view(), name='sensors_list'),
    # Sensors detail view
    path('sensors/detail/<int:pk>/', views.SensorsDetailView.as_view(), name='sensors_detail'),
    # Sensors create view
    path('sensors/create/', views.SensorsCreateModelFormView.as_view(), name='sensors_create'),
    # Sensors update view
    path('sensors/update/<int:pk>/', views.SensorsUpdateModelFormView.as_view(), name='sensors_update'),
    # Sensor's delete view
    path('sensors/delete/<int:pk>/', views.SensorsDeleteView.as_view(), name='sensors_delete'),
    
    path("profile/", include("accounts.urls")),
    
    # for file uploading at 2022/11/9
    path('upload/', views.Upload.as_view(), name='upload'),
    # path('upload/', views.upload, name='upload'),
    path('upload/complete/', views.UploadComplete.as_view(), name='upload_complete'),
    # path('upload/complete/', views.upload_complete, name='upload_complete'),
    # path('load/', views.Load.as_view(), name='load'),
    # path('download/', views.download, name='download'),
    
    path('ajax_number/', views.ajax_number, name='ajax_number'),
    
    # # Display path root for all sensor devices belong in each site/location
    # path('sensor/device/list/<int:pk>/', views.SensorDeviceListView.as_view(), name='sensor_device_list'),
    # # 2022/12/14 Draw chart by using another chart tool
    # # path('sensor/device/list/<int:pk>/chart', views.update_chart, name='chart'),
    
    # # Display all sensor devices
    # path('sensor/list', views.SensorListView.as_view(), name='sensor_list'),
    # # 2022/12/2 SensorDeviceDetail detail contents of all sensor devices list
    # path('sensor/<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    # path('sensor/device/detail/<int:pk>/', views.SensorDeviceDetailView.as_view(), name='sensor_device_detail'),
    # # Display location list view at 2022/11/28
    # path('sensor/location/list', views.LocationListView.as_view(), name='location_list'),
    # # Detail view with PK
    # # path('sensor/detail/<uuid:pk>/', views.SensorDetailView.as_view(), name='sensor_detail'),
    # path('sensor/location/detail/<int:pk>/', views.LocationDetailView.as_view(), name='location_detail'),
    # # path('sensor/detail/<int:pk>/', views.SensorDeviceDetailView.as_view(), name='sensor_device_detail'),
    # # Create view / Setting view
    # # path('sensor/setting/', views.SensorSettingView.as_view(), name='sensor_setting'),
    # path('sensor/location/setting/', views.LocationSettingView.as_view(), name='location_setting'),
 
    # # Create complete / Setting done
    # path('sensor/setting/done/', views.SensorSettingDoneView.as_view(), name='sensor_setting_done'),
    # path('sensor/location/setting/done/', views.LocationSettingDoneView.as_view(), name='location_setting_done'),
 
    # # Update view with PK
    # # path('sensor/update/<uuid:pk>/', views.SensorUpdateView.as_view(), name='sensor_update'),
    # # path('sensor/location/setting/<int:pk>/', views.LocationSettingView.as_view(), name='location_setting'),
    # path('sensor/location/update/<int:pk>/', views.LocationUpdateView.as_view(), name='location_update'),
    
    # # Delete view with PK
    # # path('sensor/delete/<uuid:pk>/', views.SensorDeleteView.as_view(), name='sensor_delete'),
    # path('sensor/location/delete/<int:pk>/', views.LocationDeleteView.as_view(), name='location_delete'),
    
    # # 以下を追記(views.pyのcall_write_data()にデータを送信できるようにする)
    # path("ajax/", views.call_write_data, name="call_write_data"),
]

record/urls.py
from django.urls import path
from . import views

app_name='record'
urlpatterns = [
    path('list/', views.RecordListView.as_view(), name='record_list'),
    path('detail/<int:pk>/', views.RecordDetailView.as_view(), name='record_detail'),
    path('update/<int:pk>/', views.RecordUpdateView.as_view(), name='record_update'),
    path('create/', views.RecordCreateView.as_view(), name='record_create'),
    path('delete/<int:pk>/', views.RecordDeleteView.as_view(), name='record_delete'),
    # Articles
    path('record/article/', views.RecordArticleView.as_view(), name='record_article'),
    path('record/python/', views.RecordPythonView.as_view(), name='record_python'),
    path('record/server/', views.RecordServerView.as_view(), name='record_server'),   
]

record/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
#import datetime

class Record(models.Model):
    class Meta:
        db_table='record'
        verbose_name='開発記録'
        verbose_name_plural='記録一覧'
        
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title=models.CharField(verbose_name='標題',max_length=200)
    text=models.TextField(verbose_name='記事')
    created_date=models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    
    #def __str__(self):
        # 管理画面で表示する時間に9時間加算する
    #    datetime_now = self.update_at + datetime.timedelta(hours=9)
    #    datetime_now = datetime_now.strftime("%Y/%m/%d %H:%M:%S")
    #    return f'{self.name} {datetime_now}'

record/forms.py
from django import forms
from .models import Record

class RecordForm(forms.ModelForm):
    class Meta:
        model=Record
        fields=('title', 'text',)
#        widgets={
#            'date' : forms.DateInput(attrs={'class' : 'form-control'}),
#            'title' : forms.TextInput(attrs={'class' : 'form-control'}),
#            'text' : forms.TextInput(attrs={'class' : 'form-control'}),
#        }

record/views.py
from django.shortcuts import render,redirect,get_object_or_404
# Create your views here.
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Record
from .forms import RecordForm
from django.utils import timezone

# Record list view
class RecordListView(ListView):
    template_name='record/record_list.html'
    model=Record
    
    # the selected records are reordered  by "published_date"
    def get_queryset(self):
        qs = Record.objects.all()
        # ユーザーがログインしていれば、リストを表示する
        # q = self.request.GET.get("search")
        # qs = Record.objects.search(query=q)
        # if self.request.user.is_authenticated:
        #     qs = qs.filter(Q(public=True)|Q(user=self.request.user))
        # else:
        #     qs = qs.filter(public=True)
        # qs = qs.order_by("-published_date")[:7]
        qs = qs.order_by("-published_date")
        return qs

# Detail view of record    
class RecordDetailView(DetailView):
    template_name='record/record_detail.html'
    model=Record

# Updating vew of record
# class RecordUpdateView(LoginRequiredMixin,UpdateView):
class RecordUpdateView(UpdateView):
    template_name = 'record/record_update.html'
    model = Record
    #form_class=RecordForm
    fields = ('title', 'text',)
    success_url = reverse_lazy('record:record_list')
 
    def form_valid(self, form):
        record = form.save(commit=False)
        # record.author = self.request.user
        record.published_date = timezone.now()
        record.save()
        return super().form_valid(form)

# Creating view of a new record
# class RecordCreateView(LoginRequiredMixin,CreateView):
class RecordCreateView(CreateView):
    template_name='record/record_create.html'
    form_class=RecordForm
    success_url=reverse_lazy('record:record_list')
    
    def form_valid(self, form):
        record = form.save(commit=False)
        # record.author = self.request.user
        record.published_date = timezone.now()
        record.save()
        return super().form_valid(form)
 
# class RecordDeleteView(LoginRequiredMixin,DeleteView):
class RecordDeleteView(DeleteView):
    template_name = 'record/record_delete.html'
    model = Record
    # form_class=RecordForm
    success_url = reverse_lazy('record:record_list')
    
class RecordArticleView(TemplateView):
    template_name='record/record_article.html'
    
class RecordPythonView(TemplateView):
    template_name='record/record_python.html'
    
class RecordServerView(TemplateView):
    template_name='record/record_server.html'

templates/record/base.html
{% load static %}
<html>
    <head>
        <title>My First WEB application</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Gothic' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/record.css' %}">
    </head>

    <body>
        <div class="page-header">  
            <h1><a href="/">遠隔監視システム [開発記録画面]</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                <!-- この中に各HTMLのbodyがはいる -->
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

templates/record/record_article.html
{% extends 'record/record_base.html' %}

{% block content %}
<div class="container">
    <br>
    <h3>遠隔監視システム開発に関する記録を残します。</h3>
    <div><big>
            <span>実験検証用に構築したサーバーは、Linux(Ubuntu)OSで構成しています。</span>
            <br><span>なぜLinux ? ➡ 余計な費用をかけずに、低コストで実現できることが最大の理由です。 </span>
            <br><span>また、オープンソースOSのため、無料で長期サポートのサーバーを構築できます。</span>
    </big></div>
    <br>
    <div>
        <h3>■Linuxサーバーの基本構成</h3>
        <a href="{% url 'record:record_server' %}">Webサーバー構築</a>
        <br>・Ubuntu 22.04.1 LTS: Linux サーバーOS (サポート期間 ~April/2027)
        <br>・OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022: SSHサーバー機能
        <br>・Apache2 2.4.52: Webサーバー機能
        <br>・ProFTPD2 1.3.7c: FTPサーバー機能
        <br>
        <span>=参考記事=</span>
        <br><a href="https://www.ubuntulinux.jp/home" target="_blank" rel="noopener noreferrer">ubuntu Japanese Team</a>
        <br><a href="https://shell-mag.com/portal-linuxserver/" target="_blank" rel="noopener noreferrer">UbuntuではじめるLinuxサーバー</a>
        <br><a href="https://www.fenet.jp/infla/column/server/linux%E3%81%A7%E3%81%AE%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E6%A7%8B%E7%AF%89%E3%81%A8%E3%81%AF%EF%BC%9F%E3%81%8A%E3%81%99%E3%81%99%E3%82%81%E3%81%AE%E3%83%87%E3%82%A3%E3%82%B9%E3%83%88%E3%83%AA" target="_blank" rel="noopener noreferrer">Linuxでのサーバー構築とは？おすすめのディストリビューション11選</a>
    </div>
    <br>
    <div>        
        <h3>■Webアプリ作成環境構築</h3>
        <big>
            <span>このWebアプリは、Pythonを開発言語としてDjangoフレームワークで構成しています</span>
            <br><span>なぜPython, Django ? ➡ オープンソースのライブラリーが豊富で低コスト</span>
            <br><span>無料かつ短期間でのWebアプリ構築が期待できる</span>
        </big>
        <p>・Python3 3.10.6: 開発言語</p>
        <p>・Django 3.2.12: Webアプリフレームワーク</p>
        <p>・VScode 1.74.1: コードエディター(Visual Studio Code)</p>
        <span>=参考記事=</span>
        <br><a href="https://www.itmanage.co.jp/column/web-application/" target="_blank" rel="noopener noreferrer">WEBアプリケーションとは？ 仕組みを開発やフレームワークを例に解説</a>
        <br><a href="https://yunifusu.com/programming/webapp_make_01/" target="_blank" rel="noopener noreferrer">【Python×Django×Docker×VScode】WEBアプリ作成フロー</a>
    </div>
    <br>
    <div>
        <br>
        <div>
            <h3>■Webアプリ開発準備</h3>
            ●Pyhton学習
            <br><a href="{% url 'record:record_python' %}">Pythonの設定</a>
            <br><a href="https://docs.python.org/ja/3/tutorial/" target="_blank" rel="noopener noreferrer">Python公式チュートリアル日本語訳「Python チュートリアル」</a>
            <br><a href="https://qiita.com/KatsunoriNakamura/items/b465b0cf05b1b7fd4975" target="_blank" rel="noopener noreferrer">pdf版テキスト「Python」</a>
            <br><a href="https://note.nkmk.me/python-post-summary/" target="_blank" rel="noopener noreferrer">Python関連記事まとめ</a>
            <br>●Django学習
            <br><a href="https://docs.djangoproject.com/ja/4.1/intro/tutorial01/" target="_blank" rel="noopener noreferrer">Django公式チュートリアル「はじめての Django アプリ作成、その 1」</a>   
            <br><a href="https://djangogirls.org/en/" target="_blank" rel="noopener noreferrer">Django Girls, </a>
            <a href="https://tutorial.djangogirls.org/ja/" target="_blank" rel="noopener noreferrer">Django Girls のチュートリアル日本語訳版</a>
            <br>●HTML/CSS/Javascript学習
            <br><a href="https://codeprep.jp/books/1" target="_blank" rel="noopener noreferrer">HTML入門 基本要素(タグ)編</a>
            <br><a href="http://www.htmq.com/" target="_blank" rel="noopener noreferrer">HTMLクイックリファレンス</a>
            <br><a href="https://codeprep.jp/books/2" target="_blank" rel="noopener noreferrer">CSS入門 基本スタイリング編</a>
            <br><a href="https://codeprep.jp/books/3" target="_blank" rel="noopener noreferrer">JavaScript入門 基本操作編</a>    
        </div>
        <br>
        <div>
            <h3>■Webアプリ開発</h3>
            <br>●アプリケーション(Django)開発環境を構築
            <br><a href="https://tutorial.djangogirls.org/ja/installation/" target="_blank" rel="noopener noreferrer">Django Girls のチュートリアル～インストール</a>
            <br>●開発用と本番用に環境を分離して、開発用にdjango-debug-tool-barを導入する
            <br><a href="https://self-methods.com/django-settings-split/" target="_blank" rel="noopener noreferrer">【django】開発・本番環境用にsettings.pyを分割</a>
            <br><a href="https://self-methods.com/django-debug-toolbar-setting/" target="_blank" rel="noopener noreferrer">【django-debug-toolbar】の使い方と設定方法</a>
            <br>
            <br><a href="https://qiita.com/kkkei257/items/b3292b443699ecfb148f" target="_blank" rel="noopener noreferrer">Django環境でHTMLからPythonコードを実行</a>              
            <br><a href="https://codor.co.jp/django/" target="_blank" rel="noopener noreferrer">Code for Django</a>
            <br><a href="https://office54.net/python/django/views-request-post" target="_blank" rel="noopener noreferrer">【Django】views.py: request.POST/GETから値を取得する方法（get、getlist）</a>
            <br>●グラフを描く~Plotly
            <br><a href="https://plotly.com/graphing-libraries/" target="_blank" rel="noopener noreferrer">Plotly Open Source Graphing Libraries</a>
            <br> →JAVA Scriptによる描画
            <br><a href="https://pyhaya.hatenablog.com/entry/2021/08/15/225829" target="_blank" rel="noopener noreferrer">【Django + Plotly.js】グラフをリアルタイム更新</a>
            <br> →Pythonによる描画
            <br><a href="https://classynode.com/2021/05/plotly_secondary_y/" target="_blank" rel="noopener noreferrer">【Python + Plotly】2軸の折れ線グラフを作る方法</a>
            <br>●ユーザー管理を行う
            <br><a href="https://kosuke-space.com/django-login-required" target="_blank" rel="noopener noreferrer">【Django】ログインを必須にする</a>
            <br>●CSVファイルを扱う
            <br><a href="https://intellectual-curiosity.tokyo/2018/12/18/django%E3%81%A7%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95/" target="_blank" rel="noopener noreferrer">【Django】ファイルをアップロードする方法</a>
            <br><a href="https://intellectual-curiosity.tokyo/2018/12/19/django%E3%81%A7csv%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89%E3%81%97%E3%81%A6db%E3%81%AB%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E8%BF%BD/" target="_blank" rel="noopener noreferrer">【Django】アップロードしてDBにレコードを追加する方法</a>
            <br>●HttpreRuestに知識を得る
            <br><a href="https://codezine.jp/article/detail/14493" target="_blank" rel="noopener noreferrer">【Django】HttpRequestオブジェクトを徹底解説</a>                        
            <br>●Ajax通信機能を扱う
            <br><a href="https://www.sejuku.net/blog/25316" target="_blank" rel="noopener noreferrer">【JavaScript】reloadでページを更新する</a>            
            <br><a href="https://office54.net/python/django/django-ajax" target="_blank" rel="noopener noreferrer">【django】Ajaxによる非同期通信：動的にページ更新する方法</a>
            <br><a href="https://intellectual-curiosity.tokyo/2018/11/02/django%E3%81%A7ajax%E3%81%AB%E3%82%88%E3%82%8B%E3%83%87%E3%83%BC%E3%82%BF%E6%9B%B4%E6%96%B0%E3%82%92%E8%A1%8C%E3%81%86%E6%96%B9%E6%B3%95/" target="_blank" rel="noopener noreferrer">【django】DjangoでAjaxによるデータ更新を行う方法</a>
            <br>●時間を管理する
            <br><a href="https://ssrv.net/tech/python-file-watchdog/">【Python】フォルダ内の変更を監視する Watchdog の使用例</a>
            <br>●トラブルシューティング
            <br><a href="https://rurukblog.com/post/django-time-lags/" target="_blank" rel="noopener noreferrer">【Django】datetimeとDBから取得した時間がずれる</a>
            <br>== UTCとJSTの扱いをあなどるな! ==
            <br><a href="https://docs.python.org/ja/3/library/datetime.html?highlight=datetime%20strptime#datetime.datetime.strptime" target="_blank" rel="noopener noreferrer">【Python】datetime --- 基本的な日付型および時間型</a>
            <br><a href="https://qiita.com/xza/items/9618e25a8cb08c44cdb0" target="_blank" rel="noopener noreferrer">【Python】日付、時刻の処理</a>
            <br><a href="https://dateutil.readthedocs.io/en/stable/tzwin.html" target="_blank" rel="noopener noreferrer">【Python】dateutilthedoc</a>  
        </div>
    </div>
    <br>
</div>
{% endblock %}

templates/record/record_base.html
{% load static %}
<html>
    <head>
        <title>Remote monitoring system' development record</title>
        {% include "css.html" %}
    </head>

    <body>
        {% include "nav.html" %}
        <div class="page-header">  
            <h1>遠隔監視システム [開発記録画面]</h1>
        </div>
        <div class="content container">
            {% block content %}
            <!-- この中に各HTMLのbodyがはいる -->
            {% endblock %}
        </div>
        {% include "footer.html" %}
        {% include "js.html" %}
    </body>
</html>

templates/record/record_create.html
{% extends 'record/record_base.html' %}

{% block content %}
    <h2>新しい記録</h2>
    <div class="container my-3" style="max-width:700px;">
        <form method="POST" class="record-form"> 
        {% csrf_token %}
        {{ form.as_p }}
            {% if record %}
                <button class="form-control btn btn-primary" type="submit">編集結果を保存</button>
            {% else %}
                <button class="form-control btn btn-primary" type="submit">登録</button>
            {% endif %}
        </form>
    </div>

{% endblock %}

templates/record/record_delete.html
{% extends 'record/record_base.html' %}
{% block content %}

    <h1>削除の確認</h1>
    <form method="POST">{% csrf_token %}
        <p>タイトル「{{ record.title }}」を削除します。よろしければ実行ボタンを押してください。</p>
        <input type="submit" value="削除実行">
    </form>

{% endblock %}

templates/record/record_detail.html
{% extends 'record/record_base.html' %}

{% block content %}
<big><p><a href="{% url 'record:record_create' %}"><span class="glyphicon glyphicon-plus"></span>新規作成</a></p></big>
<div class="record">
    <h3>＜標題＞「{{ record.title }}」</h3>
    <div>
        <a class="btn btn-default" href="{% url 'record:record_update' record.pk %}"><span class="glyphicon glyphicon-pencil"></span> この記録を編集</a>
        <a class="btn btn-default" href="{% url 'record:record_list' %}"><span class="glyphicon glyphicon-list-alt"></span> リスト表示に戻る</a>
        <a class="btn btn-default" href="{% url 'record:record_delete' record.pk %}"><span class="glyphicon glyphicon-remove-sign"></span> この記録を削除</a>    
    </div>
    <br>
    {% if record.published_date %}
    <div class="date">
        <p>＜日付＞
        {{ record.published_date }}</p>
    </div>
    {% endif %}
    <p>＜記事＞</p>
    <big><p>{{ record.text|linebreaksbr }}</p></big>

</div> 
{% endblock %}

templates/record/record_list.html
{% extends 'record/record_base.html' %}

{% block content %}
<div class="container">
    <br>
    <div>
        <big><p><a href="{% url 'record:record_create' %}"><span class="glyphicon glyphicon-plus"></span>新規作成</a></p></big>
    </div>
    <br>
    <div>
    {% for record in record_list %}
        <div class=".record">
            <div class="date">
                <p>更新日: {{ record.published_date }}</p>
                <h4><a href="{% url 'record:record_detail' record.pk %}">{{ record.title }}</a></h4>
            </div>
            <p>{{ record.text|linebreaksbr }}</p>
            <br>
        </div>
    {% endfor %}
    </div>
</div>    
{% endblock %}

templates/record/record_server.html
{% extends 'record/record_base.html' %}

{% block content %}
    <h1>Webサーバー構築</h1>
    <div>
        <p>
            WebサイトやWebアプリケーションは、大きく分けて、フロントエンド
            とバックエンドという2つの仕組みによって動く。
            Webにおけるフロントエンドとバックエンドとはどのようなものなのか？
        </p>   
        <p>
            フロントエンドとは、WebサービスやWebアプリケーションで直接ユーザーの
            目に触れる部分のこと。WebサイトやWebアプリケーションなどでユーザーが
            文字を入力したり、ボタンをクリックしたりする部分や、バックエンドの
            ソフトウエアと直接やり取りをする部分のことを指す。クライアントサイド
            とも呼ばれ、Webブラウザ側でプログラムを実行している。
            フロントエンドの開発で利用する言語は主にHTMLやCSS、JavaScript、
            TypeScript。また、最近はReactやVue.js、Next.js、Nuxt.jsなど、
            JavaScriptのフレームワークやライブラリを利用しての開発も増えている。
        </p>
        <p>
            対して、バックエンドは、サーバーサイド（Webサーバー側）やデータベース
            のシステムなど、ユーザーの目に見えない部分のこと。ユーザーが入力した
            内容などのデータ処理やデータベースへの保存、検索結果の出力といったこと
            を実行する。ユーザーからは見えない後方の部分の処理を担っていることが、
            バックエンドと呼ばれている理由。
            バックエンドの開発で利用する言語には、JavaやJavaScript、PHP、Python、
            Rubyといったプログラミング言語があり、開発効率を高めるための
            各種フレームワークを利用して開発が行われる。
        </p>
    </div>
    <a href="{% url 'record_article' %}">前ページに戻る</a>
{% endblock %}

templates/record/record_update.html
{% extends 'record/record_base.html' %}

{% block content %}
<big><p><a href="{% url 'record:record_create' %}"><span class="glyphicon glyphicon-plus"></span>新規作成</a></p></big>
    <h1>記録の編集</h1>
    <div class="container my-3" style="max-width:700px;">
        <form method="POST" class="record-form"> 
        {% csrf_token %}
        {{ form.as_p }}
            {% if record %}
                <button class="form-control btn btn-primary" type="submit">編集結果を保存</button>
            {% else %}
                <button class="form-control btn btn-primary" type="submit">登録</button>
            {% endif %}
        </form>
    </div>
{% endblock %}