config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from .settings.base import DEBUG

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('record/', include('record.urls')),
    path('devolution/', include('devolution.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
#        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ]

main/urls.py
from django.urls import path,include
from . import views
# from .views import LocationCreateFormView

app_name='main'
urlpatterns=[
    # Top index view
    path('', views.IndexView.as_view(), name='main_index'),
    # path('user/', views.user_view, name='main_user'),
    path('other/', views.other_view, name='main_other'),
    # Main detail view
    path('detail/<int:pk>/', views.MainDetailView.as_view(), name='main_detail'),
    path('user/', views.MainDetailView.as_view(), name='main_user'),
    # Location list view
    path('location/list', views.LocationListView.as_view(), name='location_list'),
    # Location list view
    # path('location/select', views.LocationSelectView.as_view(), name='location_select'),
    # Detail view
    path('location/detail/<int:pk>/', views.LocationDetailView.as_view(), name='location_detail'),
    # Location create view
    path('location/create/', views.LocationCreateModelFormView.as_view(), name='location_create'),
    # Location update view
    path('location/update/<int:pk>/', views.LocationUpdateModelFormView.as_view(), name='location_update'),    
    # Location delete view
    path('location/delete/<int:pk>/', views.LocationDeleteView.as_view(), name='location_delete'),
    
    # Sensors list view
    path('sensors/list', views.SensorsListView.as_view(), name='sensors_list'),
    # Sensors detail view
    path('sensors/detail/<int:pk>/', views.SensorsDetailView.as_view(), name='sensors_detail'),
    # Sensors create view
    path('sensors/create/', views.SensorsCreateModelFormView.as_view(), name='sensors_create'),
    # Sensors update view
    path('sensors/update/<int:pk>/', views.SensorsUpdateModelFormView.as_view(), name='sensors_update'),
    # Sensor's delete view
    path('sensors/delete/<int:pk>/', views.SensorsDeleteView.as_view(), name='sensors_delete'),
    
    path("profile/", include("accounts.urls")),
    
    # for file uploading at 2022/11/9
    path('upload/', views.Upload.as_view(), name='upload'),
    # path('upload/', views.upload, name='upload'),
    path('upload/complete/', views.UploadComplete.as_view(), name='upload_complete'),
    # path('upload/complete/', views.upload_complete, name='upload_complete'),
    # path('load/', views.Load.as_view(), name='load'),
    # path('download/', views.download, name='download'),
    
    path('ajax_number/', views.ajax_number, name='ajax_number'),
    
    # # Display path root for all sensor devices belong in each site/location
    # path('sensor/device/list/<int:pk>/', views.SensorDeviceListView.as_view(), name='sensor_device_list'),
    # # 2022/12/14 Draw chart by using another chart tool
    # # path('sensor/device/list/<int:pk>/chart', views.update_chart, name='chart'),
    
    # # Display all sensor devices
    # path('sensor/list', views.SensorListView.as_view(), name='sensor_list'),
    # # 2022/12/2 SensorDeviceDetail detail contents of all sensor devices list
    # path('sensor/<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    # path('sensor/device/detail/<int:pk>/', views.SensorDeviceDetailView.as_view(), name='sensor_device_detail'),
    # # Display location list view at 2022/11/28
    # path('sensor/location/list', views.LocationListView.as_view(), name='location_list'),
    # # Detail view with PK
    # # path('sensor/detail/<uuid:pk>/', views.SensorDetailView.as_view(), name='sensor_detail'),
    # path('sensor/location/detail/<int:pk>/', views.LocationDetailView.as_view(), name='location_detail'),
    # # path('sensor/detail/<int:pk>/', views.SensorDeviceDetailView.as_view(), name='sensor_device_detail'),
    # # Create view / Setting view
    # # path('sensor/setting/', views.SensorSettingView.as_view(), name='sensor_setting'),
    # path('sensor/location/setting/', views.LocationSettingView.as_view(), name='location_setting'),
 
    # # Create complete / Setting done
    # path('sensor/setting/done/', views.SensorSettingDoneView.as_view(), name='sensor_setting_done'),
    # path('sensor/location/setting/done/', views.LocationSettingDoneView.as_view(), name='location_setting_done'),
 
    # # Update view with PK
    # # path('sensor/update/<uuid:pk>/', views.SensorUpdateView.as_view(), name='sensor_update'),
    # # path('sensor/location/setting/<int:pk>/', views.LocationSettingView.as_view(), name='location_setting'),
    # path('sensor/location/update/<int:pk>/', views.LocationUpdateView.as_view(), name='location_update'),
    
    # # Delete view with PK
    # # path('sensor/delete/<uuid:pk>/', views.SensorDeleteView.as_view(), name='sensor_delete'),
    # path('sensor/location/delete/<int:pk>/', views.LocationDeleteView.as_view(), name='location_delete'),
    
    # # 以下を追記(views.pyのcall_write_data()にデータを送信できるようにする)
    # path("ajax/", views.call_write_data, name="call_write_data"),
]

record/urls.py
from django.urls import path
from . import views

app_name='record'
urlpatterns = [
    path('list/', views.RecordListView.as_view(), name='record_list'),
    path('detail/<int:pk>/', views.RecordDetailView.as_view(), name='record_detail'),
    path('update/<int:pk>/', views.RecordUpdateView.as_view(), name='record_update'),
    path('create/', views.RecordCreateView.as_view(), name='record_create'),
    path('delete/<int:pk>/', views.RecordDeleteView.as_view(), name='record_delete'),
    # Articles
    path('record/article/', views.RecordArticleView.as_view(), name='record_article'),
    path('record/python/', views.RecordPythonView.as_view(), name='record_python'),
    path('record/server/', views.RecordServerView.as_view(), name='record_server'),   
]

main/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from .models import Location,Sensors,Result
from .forms import LocationForm,SensorsForm
from accounts.models import User
# ページへのアクセスをログインユーザーのみに制限する
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth import get_user, get_user_model
from django.contrib import messages
from django.utils import timezone
import datetime
# Chart drawing with Plotly
import os
import logging
from main import addCsv
from .forms import FileUploadForm
# from .forms import UploadFileForm
import plotly.graph_objects as go
from plotly.subplots import make_subplots
# ajax trial
from django.conf import settings
from django.http import JsonResponse

# import dateutil
# from dateutil import tz
# from dateutil.relativedelta import relativedelta
# from django.http import Http404
# from django.shortcuts import get_object_or_404
# from django.http import HttpResponseRedirect
# from .application import data_rw
# for CSV file uploading
# import csv, io
# from django.http import HttpResponse 
# from sensor.forms import FileUploadForm
# import numpy as np
# from sensor import writeCsv
# embedded watchdog module
# import sys
# import time
# from watchdog.observers import Observer
# from watchdog.events import RegexMatchingEventHandler
# from watchdog.events import LoggingEventHandler

# directory to store the uploading files
UPLOAD_DIR = os.path.join(os.path.dirname(__file__), 'static/uploads/')
# Define debug log-file
logger = logging.getLogger('development')
# logger = logging.getLogger(__name__)

# Color palette for chart drawing which prepared 10 colors
COLOR=['darkturquoise','orange','green','red','blue','brown','violet','magenta','gray','black']
# COMPANY={'saga':'A株式会社','kumamoto':'株式会社B','fukuoka':'C株式会社',}

class OwnerOnly(UserPassesTestMixin):
    def test_func(self):
        location_instance = self.get_object()
        return location_instance.user == self.request.user
    
    def handle_no_permission(self):
        messages.error(self.request,"You can edit and delete only for your's.")
        return redirect("main:location_detail", pk=self.kwargs["pk"]) 
# -----------------------------------------------------------------
def other_view(request):
    
    # user=request.user    
    users=User.objects.exclude(email=request.user)
    context={
        'users':users
    }
    return render(request, 'main/main_other.html',context)
# -----------------------------------------------------------------
# Top view, you can select a target site for remote monitoring
class IndexView(LoginRequiredMixin,generic.ListView):
    template_name='main/main_index.html'
    model=Location
    
    def get_queryset(self):
        # ここに来た時点でuser情報は取得できている @2023.3.24
        user=self.request.user
        # ログインユーザーに許可されたQuery情報を渡す
        if user.is_authenticated:
            if('fujico@kfjc.co.jp' in user.email):
                locations = Location.objects.all()
            else:
                locations = Location.objects.filter(name=user.profile.belongs)
        return locations

    # Get user infromation
    # def get_form_kwargs(self):
    #     kwgs=super().get_form_kwargs()
    #     kwgs["user"]=self.request.user    
    #     return kwgs
    # user=AnonymousUser or authenticatedUser
# -----------------------------------------------------------------
# Chart drawing function
def line_charts(x_data,y_data,start,points,legend):
    # fig=go.Figure()    
    fig = make_subplots(
        # rows=2, cols=1,
        rows=1, cols=1,
        shared_xaxes=True,
        vertical_spacing=0.2,
        specs=[[{"secondary_y": True}]]
        # specs=[[{"type": "scatter"}]]
        # specs=[[{"type": "scatter"}], [{"type": "scatter"}]]
    )
    
    fig.update_layout(
        title='直近30分(*30)間のデータ推移',
        grid=dict(
            rows=1,
            columns=1,
            pattern='independent',
            roworder='top to bottom',
        ),
        
        xaxis=dict(
            title='時間経過[minutes]',
            showline=True,
            showgrid=True,
            zeroline=True,
            showticklabels=True,
            linecolor='rgb(204,204,204)',
            linewidth=2,
            ticks='outside',
            tickcolor='rgb(204,204,204)',
            tickwidth=2,
            ticklen=5,
            tickfont=dict(
                family='Arial',
                size=12,
                color='rgb(82,82,82)',
            )  
        ),
        
        yaxis=dict(
            title='温度[℃]',
            showline=True,
            showgrid=True,
            zeroline=False,
            showticklabels=True,
            linecolor='rgb(204,204,204)',
            linewidth=2,
            autoshift=True,
            ticks='outside',
            tickcolor='rgb(204,204,204)',
            tickwidth=2,
            ticklen=5,
            tickfont=dict(
                family='Arial',
                size=12,
                color='rgb(82,82,82)',
            )  
        ),
        
        # xaxis2=dict(
        #     title='時間経過[minutes]',
        #     showline=True,
        #     showgrid=True,
        #     zeroline=True,
        #     showticklabels=True,
        #     linecolor='rgb(204,204,204)',
        #     linewidth=2,
        #     ticks='outside',
        #     tickcolor='rgb(204,204,204)',
        #     tickwidth=2,
        #     ticklen=5,
        #     tickfont=dict(
        #         family='Arial',
        #         size=12,
        #         color='rgb(82,82,82)',
        #     )  
        # ),
        
        yaxis2=dict(
            title='圧力[Pa]',
            showline=True,
            showgrid=True,
            zeroline=False,
            showticklabels=True,
            linecolor='rgb(204,204,204)',
            linewidth=2,
            autoshift=True,
            ticks='outside',
            tickcolor='rgb(204,204,204)',
            tickwidth=2,
            ticklen=5,
            tickfont=dict(
                family='Arial',
                size=12,
                color='rgb(82,82,82)',
            )  
        ),        
        
        hovermode='closest',
        autosize=True,
        showlegend=True,
        legend=dict(
            x=0.02,
            y=1.16,
            xanchor='left',
            yanchor='top',
            orientation='h',
        )
    )
    """_summary_ グラフ描画
        左軸：温度[℃]、マーカー● と 右軸：温度以外(以下のところ圧力[Pa]を準備)、マーカー■の2軸描画
        色分けが9色のみ、場合分けで20個まで描画可能
        Returns:
        _type_: _description_
    """
    for i in range(0,points):
        if(i<=9):
            # 温度 [℃]軸
            if('[℃]' in str(legend[i])):
                fig.add_trace(
                    go.Scatter(
                        x=x_data,
                        y=y_data[start-1+i],   
                        name=str(legend[i]),        # legend table
                        mode='lines+markers',
                        connectgaps=True,
                        line=dict(
                            color=COLOR[i],         # color palette
                            width=2,
                        ),
                        line_dash='solid',          # 
                        marker=dict(
                            symbol='circle',
                            color=COLOR[i],         # color palette
                            size=10,
                        ),   
                    )
                )
            # 圧力軸
            else:
                fig.add_trace(
                    go.Scatter(
                        x=x_data,
                        y=y_data[start-1+i],
                        # name='trace'+str(i+1),      
                        name='右軸: '+str(legend[i]),   # legend table
                        mode='lines+markers',
                        connectgaps=True,
                        line=dict(
                            color=COLOR[i],             # color pallet
                            width=2,
                        ),
                        line_dash='solid',
                        marker=dict(
                            symbol='square',
                            color=COLOR[i],             # color pallet
                            size=10,
                        ),   
                    ),
                    secondary_y=True,
                )                    
        elif(i<=19):
            # 温度軸
            if('[℃]' in str(legend[i])):
                fig.add_trace(
                    go.Scatter(
                        x=x_data,
                        y=y_data[start-1+i],
                        name=str(legend[i]),        # legend table
                        mode='lines+markers',
                        connectgaps=True,
                        line=dict(
                        color=COLOR[i-10],      # color pallet
                            width=2,
                        ),
                        line_dash="dot",
                        marker=dict(
                            symbol='circle',
                            color=COLOR[i-10],      # color pallet
                            size=10,
                        ),
                    )
                )
            # 圧力軸
            else:
                fig.add_trace(
                    go.Scatter(
                        x=x_data,
                        y=y_data[start-1+i],
                        # name='trace'+str(i+1),      
                        name='右軸: '+str(legend[i]),        # legend table
                        mode='lines+markers',
                        connectgaps=True,
                        line=dict(
                            color=COLOR[i-10],      # color pallet
                            width=2,
                            ),
                        line_dash="dot",
                        marker=dict(
                            symbol='square',
                            color=COLOR[i-10],      # color pallet

templates/main/_location_create_another.html
{% extends 'main/main_base.html' %}

{% block title %}遠隔監視対象を追加{% endblock %}

{% block content %}
    <h4>監視サイトを追加</h4>
    <div class="container my-3" style="max-width:700px;">
        {% comment %} <form method="POST"> {% endcomment %}
        <form method="POST" class="main-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="form-control btn btn-primary" type="submit">登録</button>
            {% comment %} <button type="submit" class="save btn btn-default">登録</button> {% endcomment %}
        </form>

        {% comment %} <br>
        <div>
            <a  class="btn btn-default" href="{% url 'record:record_create' %}"><span class="glyphicon glyphicon-pencil"></span> 開発記録を作成</a>
            <a class="btn btn-default" href="{% url 'record:record_list' %}"><span class="glyphicon glyphicon-list-alt"></span> 開発記録一覧を表示</a>
        </div> {% endcomment %}

    </div>
{% endblock %}

templates/main/_location_create_origin.html
{% extends 'main/main_base.html' %}

{% block title %}遠隔監視対象を追加{% endblock %}

{% block content %}
    <h4>監視サイトを追加</h4>
    <div class="container my-3" style="max-width:700px;">
        {% comment %} <form method="POST"> {% endcomment %}
        <form method="POST" class="main-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="form-control btn btn-primary" type="submit">登録</button>
            {% comment %} <button type="submit" class="save btn btn-default">登録</button> {% endcomment %}
        </form>

        {% comment %} <br>
        <div>
            <a  class="btn btn-default" href="{% url 'record:record_create' %}"><span class="glyphicon glyphicon-pencil"></span> 開発記録を作成</a>
            <a class="btn btn-default" href="{% url 'record:record_list' %}"><span class="glyphicon glyphicon-list-alt"></span> 開発記録一覧を表示</a>
        </div> {% endcomment %}

    </div>
{% endblock %}

templates/main/footer.html
<!-- <footer class="bg-primary"> -->
<footer class="navbar-light" style="background-color: #1c83e2;">
    <div id="footer-logo">
      <a href="#">
          <i class="bi bi-bootstrap-fill footer-logo" style="font-size: 3rem;"></i>
      </a>
    </div>
    <div class="footer-content">
        <div>
            <a href="#">
                プライバシーポリシー
           </a>
        </div>
        <div>|</div>
        <div>
            <a href="#">
                利用規約
            </a>        
        </div>
        <div>|</div>
        <div>
            <small>Copyright &copy; 2023 株式会社フジコー</small>
        </div>
    </div>
  </footer>

templates/main/location_create.html
{% extends 'main/main_base.html' %}

{% block title %}遠隔監視対象を追加{% endblock %}

{% block content %}
    <h4>監視サイトを追加</h4>
    <div class="container my-3" style="max-width:700px;">
        {% comment %} <form method="POST"> {% endcomment %}
        <form method="POST" class="main-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="form-control btn btn-primary" type="submit">登録</button>
            {% comment %} <button type="submit" class="save btn btn-default">登録</button> {% endcomment %}
        </form>

        {% comment %} <br>
        <div>
            <a  class="btn btn-default" href="{% url 'record:record_create' %}"><span class="glyphicon glyphicon-pencil"></span> 開発記録を作成</a>
            <a class="btn btn-default" href="{% url 'record:record_list' %}"><span class="glyphicon glyphicon-list-alt"></span> 開発記録一覧を表示</a>
        </div> {% endcomment %}

    </div>
{% endblock %}

templates/main/location_create_standard.html
{% extends 'main/main_base.html' %}

{% block title %}遠隔監視対象を追加{% endblock %}

{% block content %}
    <h4>監視サイトを追加</h4>
    <div class="container my-3" style="max-width:700px;">
        {% comment %} <form method="POST"> {% endcomment %}
        <form method="POST" class="main-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="form-control btn btn-primary" type="submit">登録</button>
            {% comment %} <button type="submit" class="save btn btn-default">登録</button> {% endcomment %}
        </form>

        {% comment %} <br>
        <div>
            <a  class="btn btn-default" href="{% url 'record:record_create' %}"><span class="glyphicon glyphicon-pencil"></span> 開発記録を作成</a>
            <a class="btn btn-default" href="{% url 'record:record_list' %}"><span class="glyphicon glyphicon-list-alt"></span> 開発記録一覧を表示</a>
        </div> {% endcomment %}

    </div>
{% endblock %}

templates/main/location_delete_origin.html
{% extends 'main/main_base.html' %}

{% block title %}遠隔監視対象を削除{% endblock %}

{% block content %}

    <h1>削除確認</h1>
    <form method="POST">{% csrf_token %}
        <p>タイトル「{{ location.name }}」を削除します。よろしければ実行ボタンを押してください。</p>
        <input type="submit" value="削除実行">
    </form>
    <br>
{% endblock %}

templates/main/location_detail_another.html
{% extends 'main/main_base.html' %}

{% block title %}遠隔監視対象情報{% endblock %}

{% block content %}
    <!-- <h2>{{ location.name }} 様</h2>
    <p>更新日：{{ location.updated_date }}</p>
    <h3>MEMO: {{ location.memo }}</h3> -->
    <br>
    <h2 class="card-title">{{ location.name }} 様</h2>
    <p class="card-text">【メモ】{{ location.memo }}</p>
    <small><p>更新日：{{ location.updated_date }}</p></small>
    <div class="card-body">
        <div class="w-100">
            <a href="{% url 'main:location_update' location.pk %}" class="btn btn-primary btn-sm">サイト情報を編集</a>
            <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal-{{location.pk}}">サイト情報を削除</button>
            {% include 'main/location_delete.html' %}
        </div>
    </div>
    <br>
    <div>
        <h2>ここにLocationのsiteリストを表示する。</h2>
        <h2>DB:Locationのみを参照しているので無理?</h2>
    </div>
    <br>
    <div>
        <a class="btn btn-default" href="{% url 'main:location_list' %}"><span class="glyphicon glyphicon-backward"></span> 一覧表示に戻る</a>
    </div>
    <br>
    <div>
        <a class="btn btn-default" href="{% url 'main:main_index' %}"><span class="glyphicon glyphicon-step-backward"></span> TOP頁に戻る</a>
    </div>
{% endblock %}

templates/main/location_form.html
{% extends "main/main_base.html" %}
{% block title %}
    {% if location %}
        既存サイトの編集
    {% else %}
        サイトの新規作成
    {% endif %}
{% endblock %}
{% block content %}
<div class="container my-3" style="max-width:700px;">
    <form method="POST"> 
    {% csrf_token %}
    {{ form.as_p }}
        {% if location %}
            <button class="form-control btn btn-primary" type="submit">編集結果を保存</button>
        {% else %}
            <button class="form-control btn btn-primary" type="submit">登録</button>
        {% endif %}
    </form>
</div>
{% endblock %}

templates/main/main_other.html
{% extends 'main/main_base.html' %}

{% block content %}

<div class="container">
    <br>
    <h2>ユーザー登録の情報</h2>
    <table class="table caption-top table-bordered borderless">
        <caption>登録ユーザー情報</caption>
        <thead class="table-primary table-bordered border-dark">
            <tr align="center">
                <th scope="col">ユーザー名(email)</th>
                <th scope="col">ユーザー名(任意)</th>
                <th scope="col">会社名</th>
                <th scope="col">電話</th>
                <th scope="col">最新のログイン</th>
                <th scope="col">ロケーション</th>
                <th scope="col">ログエントリー</th>
                <th scope="col">admin</th>
                <th scope="col">staff</th>
            </tr>
        </thead>
        <tbody class="table-warning table-bordered border-dark">
            {% for user in users %}
            <tr>
                <td colspan="1">{{ user }}</td>
                <td colspan="1">{{ user.profile }}</td>
                <td colspan="1">{{ user.profile.company }}</td>
                <td colspan="1">{{ user.profile.pone_number }}</td>
                <td colspan="1">{{ user.last_login }}</td>
                <td colspan="1">{{ user.location }}</td>
                <td colspan="1">{{ user.logentry }}</td>
                <td colspan="1">{{ user.admin }}</td>
                <td colspan="1">{{ user.staff }}</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot class="table-bordered borderless">
        </tfoot>
    </table>
    <br>
{% endblock %}

templates/main/sensors_create.html
{% extends 'main/main_base.html' %}

{% block content %}
<div class="container my-3" style="max-width:700px;">
    <form method="POST"> 
    {% csrf_token %}
    {{ form.as_p }}
    {% if sensors %}
        <button class="form-control btn btn-primary" type="submit">編集結果を保存</button>
    {% else %}
        <button class="form-control btn btn-primary" type="submit">登録</button>
    {% endif %}
    </form>
</div>
{% endblock %}

templates/main/sensors_detail.html
{% extends 'main/main_base.html' %}

{% block content %}

<div class="container">
    <table class="table caption-top table-bordered border-dark">
        <br>
        <h3>{{ sensors.site }} 様 {{ sensors.device }} 情報</h3>
        <caption>{{ sensors.device }} 情報</caption>
        <thead class="table-primary table-bordered border-dark">
            <tr>
                <th scope="col">現場</th>
                <th scope="col">センサー名</th>
                <th scope="col">メモ</th>
                <th scope="col">更新日</th>
                <th scope="col">登録日</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="1">{{ sensors.site.name }}</td>
                <td colspan="1">{{ sensors.device}}</td>
                <td colspan="1">{{ sensors.note }}</td>
                <td colspan="1">{{ sensors.updated_date }}</td>
                <td colspan="1">{{ sensors.created_date }}</td>
            </tr>
        </tbody>
        </table>

        <div class="mt-3 d-flex justify-content-end">
            <a href="{% url 'main:sensors_update' sensors.pk %}" class="btn btn-primary btn-sm">更新する</a>
            <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal-{{sensors.pk}}">削除する</button>
            {% include 'main/sensors_delete.html' %}
        </div>
        <div>
            <a href="{% url 'main:sensors_list' %}" class="btn btn-primary btn-sm">リスト表示に戻る</a>    
        </div>
        <br>
</div>
{% endblock %}

templates/main/sensors_update.html
{% extends "main/main_base.html" %}
{% block title %}
    {% if sensors %}
        既存センサーの編集
    {% else %}
        サイトの新規作成
    {% endif %}
{% endblock %}
{% block content %}
<div class="container my-3" style="max-width:700px;">
    <form method="POST"> 
    {% csrf_token %}
    {{ form.as_p }}
        {% if sensors %}
            <button class="form-control btn btn-primary" type="submit">編集結果を保存</button>
        {% else %}
            <button class="form-control btn btn-primary" type="submit">登録</button>
        {% endif %}
    </form>
</div>
{% endblock %}

templates/main/upload_complete.html
<!-- upload_complete.html -->
{% extends 'main/main_base.html' %}
{% block content %}
<br>
<div class="container">
    <h1>アップロード完了</h1>
    <p>※ 左上のホームボタンでTOPページに戻ってください。</p>
    <P>
        <a  class="form-control btn btn-secondary" href="{% url 'main:upload' %}"><span class="glyphicon glyphicon-book"></span>さらにアップロードする</a>
    </p>
</div>

<br>
{% endblock %}