config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from .settings.base import DEBUG

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('record/', include('record.urls')),
    path('devolution/', include('devolution.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
#        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ]

devolution/urls.py
from django.urls import path
from . import views

app_name='devolution'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('detail/<int:pk>/', views.RecordDetailView.as_view(), name='record_detail'),
    #path('update/<int:pk>/', views.RecordUpdateView.as_view(), name='record_update'),
    #path('create/', views.RecordCreateView.as_view(), name='record_create'),
    #path('delete/<int:pk>/', views.RecordDeleteView.as_view(), name='record_delete'),
    
    # Articles
    # path('article/', views.RecordArticleView.as_view(), name='record_article'),
    # path('python/', views.RecordPythonView.as_view(), name='record_python'),
    # path('server/', views.RecordServerView.as_view(), name='record_server'),   
]

main/urls.py
from django.urls import path,include
from . import views
# from .views import LocationCreateFormView

app_name='main'
urlpatterns=[
    # Top index view
    path('', views.IndexView.as_view(), name='main_index'),
    # path('user/', views.user_view, name='main_user'),
    path('other/', views.other_view, name='main_other'),
    # Main detail view
    path('detail/<int:pk>/', views.MainDetailView.as_view(), name='main_detail'),
    path('user/', views.MainDetailView.as_view(), name='main_user'),
    # Location list view
    path('location/list', views.LocationListView.as_view(), name='location_list'),
    # Location list view
    # path('location/select', views.LocationSelectView.as_view(), name='location_select'),
    # Detail view
    path('location/detail/<int:pk>/', views.LocationDetailView.as_view(), name='location_detail'),
    # Location create view
    path('location/create/', views.LocationCreateModelFormView.as_view(), name='location_create'),
    # Location update view
    path('location/update/<int:pk>/', views.LocationUpdateModelFormView.as_view(), name='location_update'),    
    # Location delete view
    path('location/delete/<int:pk>/', views.LocationDeleteView.as_view(), name='location_delete'),
    
    # Sensors list view
    path('sensors/list', views.SensorsListView.as_view(), name='sensors_list'),
    # Sensors detail view
    path('sensors/detail/<int:pk>/', views.SensorsDetailView.as_view(), name='sensors_detail'),
    # Sensors create view
    path('sensors/create/', views.SensorsCreateModelFormView.as_view(), name='sensors_create'),
    # Sensors update view
    path('sensors/update/<int:pk>/', views.SensorsUpdateModelFormView.as_view(), name='sensors_update'),
    # Sensor's delete view
    path('sensors/delete/<int:pk>/', views.SensorsDeleteView.as_view(), name='sensors_delete'),
    
    path("profile/", include("accounts.urls")),
    
    # for file uploading at 2022/11/9
    path('upload/', views.Upload.as_view(), name='upload'),
    # path('upload/', views.upload, name='upload'),
    path('upload/complete/', views.UploadComplete.as_view(), name='upload_complete'),
    # path('upload/complete/', views.upload_complete, name='upload_complete'),
    # path('load/', views.Load.as_view(), name='load'),
    # path('download/', views.download, name='download'),
    
    path('ajax_number/', views.ajax_number, name='ajax_number'),
    
    # # Display path root for all sensor devices belong in each site/location
    # path('sensor/device/list/<int:pk>/', views.SensorDeviceListView.as_view(), name='sensor_device_list'),
    # # 2022/12/14 Draw chart by using another chart tool
    # # path('sensor/device/list/<int:pk>/chart', views.update_chart, name='chart'),
    
    # # Display all sensor devices
    # path('sensor/list', views.SensorListView.as_view(), name='sensor_list'),
    # # 2022/12/2 SensorDeviceDetail detail contents of all sensor devices list
    # path('sensor/<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    # path('sensor/device/detail/<int:pk>/', views.SensorDeviceDetailView.as_view(), name='sensor_device_detail'),
    # # Display location list view at 2022/11/28
    # path('sensor/location/list', views.LocationListView.as_view(), name='location_list'),
    # # Detail view with PK
    # # path('sensor/detail/<uuid:pk>/', views.SensorDetailView.as_view(), name='sensor_detail'),
    # path('sensor/location/detail/<int:pk>/', views.LocationDetailView.as_view(), name='location_detail'),
    # # path('sensor/detail/<int:pk>/', views.SensorDeviceDetailView.as_view(), name='sensor_device_detail'),
    # # Create view / Setting view
    # # path('sensor/setting/', views.SensorSettingView.as_view(), name='sensor_setting'),
    # path('sensor/location/setting/', views.LocationSettingView.as_view(), name='location_setting'),
 
    # # Create complete / Setting done
    # path('sensor/setting/done/', views.SensorSettingDoneView.as_view(), name='sensor_setting_done'),
    # path('sensor/location/setting/done/', views.LocationSettingDoneView.as_view(), name='location_setting_done'),
 
    # # Update view with PK
    # # path('sensor/update/<uuid:pk>/', views.SensorUpdateView.as_view(), name='sensor_update'),
    # # path('sensor/location/setting/<int:pk>/', views.LocationSettingView.as_view(), name='location_setting'),
    # path('sensor/location/update/<int:pk>/', views.LocationUpdateView.as_view(), name='location_update'),
    
    # # Delete view with PK
    # # path('sensor/delete/<uuid:pk>/', views.SensorDeleteView.as_view(), name='sensor_delete'),
    # path('sensor/location/delete/<int:pk>/', views.LocationDeleteView.as_view(), name='location_delete'),
    
    # # 以下を追記(views.pyのcall_write_data()にデータを送信できるようにする)
    # path("ajax/", views.call_write_data, name="call_write_data"),
]

record/urls.py
from django.urls import path
from . import views

app_name='record'
urlpatterns = [
    path('list/', views.RecordListView.as_view(), name='record_list'),
    path('detail/<int:pk>/', views.RecordDetailView.as_view(), name='record_detail'),
    path('update/<int:pk>/', views.RecordUpdateView.as_view(), name='record_update'),
    path('create/', views.RecordCreateView.as_view(), name='record_create'),
    path('delete/<int:pk>/', views.RecordDeleteView.as_view(), name='record_delete'),
    # Articles
    path('record/article/', views.RecordArticleView.as_view(), name='record_article'),
    path('record/python/', views.RecordPythonView.as_view(), name='record_python'),
    path('record/server/', views.RecordServerView.as_view(), name='record_server'),   
]

devolution/models.py
from django.db import models

# Create your models here.

devolution/views.py
from django.shortcuts import render
# Create your views here.
from django.shortcuts import redirect
from django.views import generic
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt

# Top-view of devolution, select configuration items

class IndexView(generic.TemplateView):
    template_name='devolution/index.html'

    def get(self, request, *args, **kwargs):
        context = {
            'message': "Hello World! from View!!",
        }
        return render(request, 'devolution/index.html', context)

    # @csrf_exempt
    def post(self, request, *args, **kwargs):
        context = {
            'message': "POST method OK!!",
        }
        return render(request, 'devolution/index.html', context)
    

    

templates/devolution/base.html
<!DOCTYPE html>
<html lang="jp">
  <head>
    <meta charset="UTF-8">
    {% comment %} レスポンシブ対応: 端末にあわせて柔軟に表示する {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} Micrsoft IE対応 インストールされている最新のバージョンで表示する {% endcomment %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    {% include "css.html" %}
    {% block extra_css %}{% endblock %}

    {% comment %} 各ページのTitleを挿入する {% endcomment %}
    {% comment %} Origin were <title>Remote monitoring</title> {% endcomment %}
    <title>{% block title %}{% endblock %}</title>
    
    {% block extra_head %}{% endblock %}

  </head>

  <body>
    {% include "nav.html" %}

    {% block allauth %}
      {% if messages %}

      <div>
        {% for message in messages %}
          {% if message.tags == "error" %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
          
          {% else %}
          <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
        
          {% endif %}

          {{message}}
          <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}

      </div>

      {% endif %}
    {% endblock %}

    <div class="page-header">
      <h1>遠隔監視システム仕様書(工事中)</h1>
      <h5><span>現在時刻: </span><span id="realtime"></span></h5>
    </div>

    <!-- <div class="content container"> -->
    <!-- <div class="row"> 右サイドにコンテンツ空間を確保する -->
    <!-- <div class="col-md-8">  --><!-- bootstrapのグリッドシステム全部で合計12とｐなる-->
  {% block content %}
    
    <!-- ここに主ページが入る -->
    
  {% endblock %}

  {% include "footer.html" %}
  {% include "js.html" %}
  
  </body>
</html>

templates/devolution/devolution_index.html
{% extends 'main/main_base.html' %}

{% block content %}
<div class="container">
    <h1>遠隔監視ステム仕様書(工事中)</h1>
</div>
<div class="container">
    <div>
        <h3>■HttpRequestメソッド確認用</h3>
        <form action="/devolution/" method="post">
            {% csrf_token %}
            <div>
                <label for="name">名前</label>
                <input type="text" id="name" name="name">
            </div>
            <div>
                <label for="email">メールアドレス</label>
                <input type="mail" id="email" name="email">
            </div>
            <div>
                <label for="message">内容</label>
                <textarea id="message" name="message">{{ message }}</textarea>
            </div>
            <div>
                <input type="submit" value="送信する">
            </div>
        </form>
        <br>
        <div>
            <p><a class="btn btn-default" href="{% url 'main:upload' %}"><span class="glyphicon glyphicon-pencil"></span>データファイルをアップロード</a></p>
            <p>※グラフ描画機能確認用</p>
        </div> 
    </div>
</div>
<br>
<div class="container">
    <h3>■参考資料</h3>
    <a  class="btn btn-secondary" href="{% url 'record:record_article' %}"><span class="glyphicon glyphicon-book"></span> 開発関係情報を閲覧する</a>
    <a  class="btn btn-secondary" href="https://github.com/hamasaki0011/djangopj1.git" target="_blank" rel="noopener noreferrer"><span class="glyphicon glyphicon-book"></span> Djangoアプリ(プログラムソース)</a>
</div>
<br>    
{% endblock %}

templates/devolution/index.html
{% extends 'devolution/base.html' %}

{% block content %}

<div class="container">
    <h2>はじめに</h2>
    <h2>目次</h2>
    <form>
        <a class="btn btn-default" href="{% url 'devolution:index' %}"><span class="glyphicon glyphicon-list"></span>目次に戻る</a>
    </form>
</div>
<br>
<div class="container">
    <div>
        <h3>■HttpRequestメソッド確認用</h3>
        <form action="/devolution/" method="post">
            {% csrf_token %}
            <div>
                <label for="name">名前</label>
                <input type="text" id="name" name="name">
            </div>
            <div>
                <label for="email">メールアドレス</label>
                <input type="mail" id="email" name="email">
            </div>
            <div>
                <label for="message">内容</label>
                <textarea id="message" name="message">{{ message }}</textarea>
            </div>
            <a>
                <form action="/devolution/" method="get">
                    {% csrf_token %}
                    <input type="submit" value="POST送信する">
                </form>
            </a>
            <a>
                <form action="/devolution/" method="get">
                    {% csrf_token %}
                    <input type="submit" value="GET送信する">
                </form>
            </a>
        <br>
        <h3>■グラフ描画確認用</h3>
        <div>
            <p><a class="btn btn-default" href="{% url 'main:upload' %}"><span class="glyphicon glyphicon-pencil"></span>データファイルをアップロード</a></p>
        </div> 
    </div>
</div>
<br>
<div class="container">
    <h3>■参考資料</h3>
    <a  class="btn btn-secondary" href="{% url 'record:record_article' %}"><span class="glyphicon glyphicon-book"></span> 開発関係情報を閲覧する</a>
    <a  class="btn btn-secondary" href="https://github.com/hamasaki0011/djangopj1.git" target="_blank" rel="noopener noreferrer"><span class="glyphicon glyphicon-book"></span> Djangoアプリ(プログラムソース)</a>
</div>
<br>    
{% endblock %}